/*
 * Binance Derivatives Trading Options WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_options::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountUpdateBInner {
    #[serde(rename = "b", skip_serializing_if = "Option::is_none")]
    pub b: Option<String>,
    #[serde(rename = "m", skip_serializing_if = "Option::is_none")]
    pub m: Option<String>,
    #[serde(rename = "u", skip_serializing_if = "Option::is_none")]
    pub u: Option<String>,
    #[serde(rename = "U", skip_serializing_if = "Option::is_none")]
    pub u_uppercase: Option<i64>,
    #[serde(rename = "M", skip_serializing_if = "Option::is_none")]
    pub m_uppercase: Option<String>,
    #[serde(rename = "i", skip_serializing_if = "Option::is_none")]
    pub i: Option<String>,
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<String>,
}

impl AccountUpdateBInner {
    #[must_use]
    pub fn new() -> AccountUpdateBInner {
        AccountUpdateBInner {
            b: None,
            m: None,
            u: None,
            u_uppercase: None,
            m_uppercase: None,
            i: None,
            a: None,
        }
    }
}
