/*
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::staking::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBoostRewardsHistoryResponseRowsInner {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "bnsolHolding", skip_serializing_if = "Option::is_none")]
    pub bnsol_holding: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl GetBoostRewardsHistoryResponseRowsInner {
    #[must_use]
    pub fn new() -> GetBoostRewardsHistoryResponseRowsInner {
        GetBoostRewardsHistoryResponseRowsInner {
            time: None,
            token: None,
            amount: None,
            bnsol_holding: None,
            status: None,
        }
    }
}
