/*
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::staking::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscribeOnChainYieldsLockedProductResponse {
    #[serde(rename = "purchaseId", skip_serializing_if = "Option::is_none")]
    pub purchase_id: Option<i64>,
    #[serde(rename = "positionId", skip_serializing_if = "Option::is_none")]
    pub position_id: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl SubscribeOnChainYieldsLockedProductResponse {
    #[must_use]
    pub fn new() -> SubscribeOnChainYieldsLockedProductResponse {
        SubscribeOnChainYieldsLockedProductResponse {
            purchase_id: None,
            position_id: None,
            amount: None,
            success: None,
        }
    }
}
