/*
 * Binance Algo REST API
 *
 * OpenAPI Specification for the Binance Algo REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::algo::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryHistoricalAlgoOrdersFutureAlgoResponseOrdersInner {
    #[serde(rename = "algoId", skip_serializing_if = "Option::is_none")]
    pub algo_id: Option<i64>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "side", skip_serializing_if = "Option::is_none")]
    pub side: Option<String>,
    #[serde(rename = "positionSide", skip_serializing_if = "Option::is_none")]
    pub position_side: Option<String>,
    #[serde(rename = "totalQty", skip_serializing_if = "Option::is_none")]
    pub total_qty: Option<String>,
    #[serde(rename = "executedQty", skip_serializing_if = "Option::is_none")]
    pub executed_qty: Option<String>,
    #[serde(rename = "executedAmt", skip_serializing_if = "Option::is_none")]
    pub executed_amt: Option<String>,
    #[serde(rename = "avgPrice", skip_serializing_if = "Option::is_none")]
    pub avg_price: Option<String>,
    #[serde(rename = "clientAlgoId", skip_serializing_if = "Option::is_none")]
    pub client_algo_id: Option<String>,
    #[serde(rename = "bookTime", skip_serializing_if = "Option::is_none")]
    pub book_time: Option<i64>,
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
    #[serde(rename = "algoStatus", skip_serializing_if = "Option::is_none")]
    pub algo_status: Option<String>,
    #[serde(rename = "algoType", skip_serializing_if = "Option::is_none")]
    pub algo_type: Option<String>,
    #[serde(rename = "urgency", skip_serializing_if = "Option::is_none")]
    pub urgency: Option<String>,
}

impl QueryHistoricalAlgoOrdersFutureAlgoResponseOrdersInner {
    #[must_use]
    pub fn new() -> QueryHistoricalAlgoOrdersFutureAlgoResponseOrdersInner {
        QueryHistoricalAlgoOrdersFutureAlgoResponseOrdersInner {
            algo_id: None,
            symbol: None,
            side: None,
            position_side: None,
            total_qty: None,
            executed_qty: None,
            executed_amt: None,
            avg_price: None,
            client_algo_id: None,
            book_time: None,
            end_time: None,
            algo_status: None,
            algo_type: None,
            urgency: None,
        }
    }
}
