/*
 * Binance Sub Account REST API
 *
 * OpenAPI Specification for the Binance Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::sub_account::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteIpListForASubAccountApiKeyResponse {
    #[serde(rename = "ipRestrict", skip_serializing_if = "Option::is_none")]
    pub ip_restrict: Option<String>,
    #[serde(rename = "ipList", skip_serializing_if = "Option::is_none")]
    pub ip_list: Option<Vec<String>>,
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
}

impl DeleteIpListForASubAccountApiKeyResponse {
    #[must_use]
    pub fn new() -> DeleteIpListForASubAccountApiKeyResponse {
        DeleteIpListForASubAccountApiKeyResponse {
            ip_restrict: None,
            ip_list: None,
            update_time: None,
            api_key: None,
        }
    }
}
