/*
 * Binance Sub Account REST API
 *
 * OpenAPI Specification for the Binance Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::sub_account::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubAccountsStatusOnMarginOrFuturesResponseInner {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "isSubUserEnabled", skip_serializing_if = "Option::is_none")]
    pub is_sub_user_enabled: Option<bool>,
    #[serde(rename = "isUserActive", skip_serializing_if = "Option::is_none")]
    pub is_user_active: Option<bool>,
    #[serde(rename = "insertTime", skip_serializing_if = "Option::is_none")]
    pub insert_time: Option<i64>,
    #[serde(rename = "isMarginEnabled", skip_serializing_if = "Option::is_none")]
    pub is_margin_enabled: Option<bool>,
    #[serde(rename = "isFutureEnabled", skip_serializing_if = "Option::is_none")]
    pub is_future_enabled: Option<bool>,
    #[serde(rename = "mobile", skip_serializing_if = "Option::is_none")]
    pub mobile: Option<i64>,
}

impl GetSubAccountsStatusOnMarginOrFuturesResponseInner {
    #[must_use]
    pub fn new() -> GetSubAccountsStatusOnMarginOrFuturesResponseInner {
        GetSubAccountsStatusOnMarginOrFuturesResponseInner {
            email: None,
            is_sub_user_enabled: None,
            is_user_active: None,
            insert_time: None,
            is_margin_enabled: None,
            is_future_enabled: None,
            mobile: None,
        }
    }
}
