/*
 * Binance Sub Account REST API
 *
 * OpenAPI Specification for the Binance Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::sub_account::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMovePositionHistoryForSubAccountResponseFutureMovePositionOrderVoListInner {
    #[serde(rename = "fromUserEmail", skip_serializing_if = "Option::is_none")]
    pub from_user_email: Option<String>,
    #[serde(rename = "toUserEmail", skip_serializing_if = "Option::is_none")]
    pub to_user_email: Option<String>,
    #[serde(rename = "productType", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<String>,
    #[serde(rename = "positionSide", skip_serializing_if = "Option::is_none")]
    pub position_side: Option<String>,
    #[serde(rename = "side", skip_serializing_if = "Option::is_none")]
    pub side: Option<String>,
    #[serde(rename = "timeStamp", skip_serializing_if = "Option::is_none")]
    pub time_stamp: Option<i64>,
}

impl GetMovePositionHistoryForSubAccountResponseFutureMovePositionOrderVoListInner {
    #[must_use]
    pub fn new() -> GetMovePositionHistoryForSubAccountResponseFutureMovePositionOrderVoListInner {
        GetMovePositionHistoryForSubAccountResponseFutureMovePositionOrderVoListInner {
            from_user_email: None,
            to_user_email: None,
            product_type: None,
            symbol: None,
            price: None,
            quantity: None,
            position_side: None,
            side: None,
            time_stamp: None,
        }
    }
}
