/*
 * Binance Sub Account REST API
 *
 * OpenAPI Specification for the Binance Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::sub_account::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuerySubAccountTransactionStatisticsResponse {
    #[serde(rename = "recent30BtcTotal", skip_serializing_if = "Option::is_none")]
    pub recent30_btc_total: Option<String>,
    #[serde(
        rename = "recent30BtcFuturesTotal",
        skip_serializing_if = "Option::is_none"
    )]
    pub recent30_btc_futures_total: Option<String>,
    #[serde(
        rename = "recent30BtcMarginTotal",
        skip_serializing_if = "Option::is_none"
    )]
    pub recent30_btc_margin_total: Option<String>,
    #[serde(rename = "recent30BusdTotal", skip_serializing_if = "Option::is_none")]
    pub recent30_busd_total: Option<String>,
    #[serde(
        rename = "recent30BusdFuturesTotal",
        skip_serializing_if = "Option::is_none"
    )]
    pub recent30_busd_futures_total: Option<String>,
    #[serde(
        rename = "recent30BusdMarginTotal",
        skip_serializing_if = "Option::is_none"
    )]
    pub recent30_busd_margin_total: Option<String>,
    #[serde(rename = "tradeInfoVos", skip_serializing_if = "Option::is_none")]
    pub trade_info_vos:
        Option<Vec<models::QuerySubAccountTransactionStatisticsResponseTradeInfoVosInner>>,
}

impl QuerySubAccountTransactionStatisticsResponse {
    #[must_use]
    pub fn new() -> QuerySubAccountTransactionStatisticsResponse {
        QuerySubAccountTransactionStatisticsResponse {
            recent30_btc_total: None,
            recent30_btc_futures_total: None,
            recent30_btc_margin_total: None,
            recent30_busd_total: None,
            recent30_busd_futures_total: None,
            recent30_busd_margin_total: None,
            trade_info_vos: None,
        }
    }
}
