/*
 * Binance Crypto Loan REST API
 *
 * OpenAPI Specification for the Binance Crypto Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::crypto_loan::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFlexibleLoanCollateralAssetsDataResponseRowsInner {
    #[serde(rename = "collateralCoin", skip_serializing_if = "Option::is_none")]
    pub collateral_coin: Option<String>,
    #[serde(rename = "initialLTV", skip_serializing_if = "Option::is_none")]
    pub initial_ltv: Option<String>,
    #[serde(rename = "marginCallLTV", skip_serializing_if = "Option::is_none")]
    pub margin_call_ltv: Option<String>,
    #[serde(rename = "liquidationLTV", skip_serializing_if = "Option::is_none")]
    pub liquidation_ltv: Option<String>,
    #[serde(rename = "maxLimit", skip_serializing_if = "Option::is_none")]
    pub max_limit: Option<String>,
}

impl GetFlexibleLoanCollateralAssetsDataResponseRowsInner {
    #[must_use]
    pub fn new() -> GetFlexibleLoanCollateralAssetsDataResponseRowsInner {
        GetFlexibleLoanCollateralAssetsDataResponseRowsInner {
            collateral_coin: None,
            initial_ltv: None,
            margin_call_ltv: None,
            liquidation_ltv: None,
            max_limit: None,
        }
    }
}
