/*
 * Binance Derivatives Trading Portfolio Margin Pro REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin Pro REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_portfolio_margin_pro::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioMarginProTieredCollateralRateResponseInnerCollateralInfoInner {
    #[serde(rename = "tierFloor", skip_serializing_if = "Option::is_none")]
    pub tier_floor: Option<String>,
    #[serde(rename = "tierCap", skip_serializing_if = "Option::is_none")]
    pub tier_cap: Option<String>,
    #[serde(rename = "collateralRate", skip_serializing_if = "Option::is_none")]
    pub collateral_rate: Option<String>,
    #[serde(rename = "cum", skip_serializing_if = "Option::is_none")]
    pub cum: Option<String>,
}

impl PortfolioMarginProTieredCollateralRateResponseInnerCollateralInfoInner {
    #[must_use]
    pub fn new() -> PortfolioMarginProTieredCollateralRateResponseInnerCollateralInfoInner {
        PortfolioMarginProTieredCollateralRateResponseInnerCollateralInfoInner {
            tier_floor: None,
            tier_cap: None,
            collateral_rate: None,
            cum: None,
        }
    }
}
