/*
 * Binance Derivatives Trading Portfolio Margin Pro REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin Pro REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_portfolio_margin_pro::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryPortfolioMarginAssetIndexPriceResponseInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "assetIndexPrice", skip_serializing_if = "Option::is_none")]
    pub asset_index_price: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
}

impl QueryPortfolioMarginAssetIndexPriceResponseInner {
    #[must_use]
    pub fn new() -> QueryPortfolioMarginAssetIndexPriceResponseInner {
        QueryPortfolioMarginAssetIndexPriceResponseInner {
            asset: None,
            asset_index_price: None,
            time: None,
        }
    }
}
