/*
 * Binance Derivatives Trading Portfolio Margin Pro REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin Pro REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_portfolio_margin_pro::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RedeemBfusdForPortfolioMarginResponse {
    #[serde(rename = "fromAsset", skip_serializing_if = "Option::is_none")]
    pub from_asset: Option<String>,
    #[serde(rename = "targetAsset", skip_serializing_if = "Option::is_none")]
    pub target_asset: Option<String>,
    #[serde(rename = "fromAssetQty", skip_serializing_if = "Option::is_none")]
    pub from_asset_qty: Option<f32>,
    #[serde(rename = "targetAssetQty", skip_serializing_if = "Option::is_none")]
    pub target_asset_qty: Option<f32>,
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<f32>,
}

impl RedeemBfusdForPortfolioMarginResponse {
    #[must_use]
    pub fn new() -> RedeemBfusdForPortfolioMarginResponse {
        RedeemBfusdForPortfolioMarginResponse {
            from_asset: None,
            target_asset: None,
            from_asset_qty: None,
            target_asset_qty: None,
            rate: None,
        }
    }
}
