/*
 * Binance Wallet REST API
 *
 * OpenAPI Specification for the Binance Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::wallet::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryUserUniversalTransferHistoryResponse {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::QueryUserUniversalTransferHistoryResponseRowsInner>>,
}

impl QueryUserUniversalTransferHistoryResponse {
    #[must_use]
    pub fn new() -> QueryUserUniversalTransferHistoryResponse {
        QueryUserUniversalTransferHistoryResponse {
            total: None,
            rows: None,
        }
    }
}
