/*
 * Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_usds_futures::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialBookDepthStreamsResponse {
    #[serde(rename = "e", skip_serializing_if = "Option::is_none")]
    pub e: Option<String>,
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e_uppercase: Option<i64>,
    #[serde(rename = "T", skip_serializing_if = "Option::is_none")]
    pub t_uppercase: Option<i64>,
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    #[serde(rename = "U", skip_serializing_if = "Option::is_none")]
    pub u_uppercase: Option<i64>,
    #[serde(rename = "u", skip_serializing_if = "Option::is_none")]
    pub u: Option<i64>,
    #[serde(rename = "pu", skip_serializing_if = "Option::is_none")]
    pub pu: Option<i64>,
    #[serde(rename = "b", skip_serializing_if = "Option::is_none")]
    pub b: Option<Vec<Vec<String>>>,
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<Vec<Vec<String>>>,
}

impl PartialBookDepthStreamsResponse {
    #[must_use]
    pub fn new() -> PartialBookDepthStreamsResponse {
        PartialBookDepthStreamsResponse {
            e: None,
            e_uppercase: None,
            t_uppercase: None,
            s: None,
            u_uppercase: None,
            u: None,
            pu: None,
            b: None,
            a: None,
        }
    }
}
