/*
 * Binance Fiat REST API
 *
 * OpenAPI Specification for the Binance Fiat REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::fiat::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFiatPaymentsHistoryResponseDataInner {
    #[serde(rename = "orderNo", skip_serializing_if = "Option::is_none")]
    pub order_no: Option<String>,
    #[serde(rename = "sourceAmount", skip_serializing_if = "Option::is_none")]
    pub source_amount: Option<String>,
    #[serde(rename = "fiatCurrency", skip_serializing_if = "Option::is_none")]
    pub fiat_currency: Option<String>,
    #[serde(rename = "obtainAmount", skip_serializing_if = "Option::is_none")]
    pub obtain_amount: Option<String>,
    #[serde(rename = "cryptoCurrency", skip_serializing_if = "Option::is_none")]
    pub crypto_currency: Option<String>,
    #[serde(rename = "totalFee", skip_serializing_if = "Option::is_none")]
    pub total_fee: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "paymentMethod", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<String>,
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i64>,
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
}

impl GetFiatPaymentsHistoryResponseDataInner {
    #[must_use]
    pub fn new() -> GetFiatPaymentsHistoryResponseDataInner {
        GetFiatPaymentsHistoryResponseDataInner {
            order_no: None,
            source_amount: None,
            fiat_currency: None,
            obtain_amount: None,
            crypto_currency: None,
            total_fee: None,
            price: None,
            status: None,
            payment_method: None,
            create_time: None,
            update_time: None,
        }
    }
}
