/*
 * Binance VIP Loan REST API
 *
 * OpenAPI Specification for the Binance VIP Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::vip_loan::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBorrowInterestRateResponseInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(
        rename = "flexibleDailyInterestRate",
        skip_serializing_if = "Option::is_none"
    )]
    pub flexible_daily_interest_rate: Option<String>,
    #[serde(
        rename = "flexibleYearlyInterestRate",
        skip_serializing_if = "Option::is_none"
    )]
    pub flexible_yearly_interest_rate: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
}

impl GetBorrowInterestRateResponseInner {
    #[must_use]
    pub fn new() -> GetBorrowInterestRateResponseInner {
        GetBorrowInterestRateResponseInner {
            asset: None,
            flexible_daily_interest_rate: None,
            flexible_yearly_interest_rate: None,
            time: None,
        }
    }
}
