/*
 * Binance Mining REST API
 *
 * OpenAPI Specification for the Binance Mining REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::mining::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcquiringAlgorithmResponseDataInner {
    #[serde(rename = "algoName", skip_serializing_if = "Option::is_none")]
    pub algo_name: Option<String>,
    #[serde(rename = "algoId", skip_serializing_if = "Option::is_none")]
    pub algo_id: Option<i64>,
    #[serde(rename = "poolIndex", skip_serializing_if = "Option::is_none")]
    pub pool_index: Option<i64>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl AcquiringAlgorithmResponseDataInner {
    #[must_use]
    pub fn new() -> AcquiringAlgorithmResponseDataInner {
        AcquiringAlgorithmResponseDataInner {
            algo_name: None,
            algo_id: None,
            pool_index: None,
            unit: None,
        }
    }
}
