/*
 * Binance C2C REST API
 *
 * OpenAPI Specification for the Binance C2C REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

pub mod get_c2_c_trade_history_response;
pub use self::get_c2_c_trade_history_response::GetC2CTradeHistoryResponse;
pub mod get_c2_c_trade_history_response_data_inner;
pub use self::get_c2_c_trade_history_response_data_inner::GetC2CTradeHistoryResponseDataInner;
