/*
 * Binance Gift Card REST API
 *
 * OpenAPI Specification for the Binance Gift Card REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::gift_card::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RedeemABinanceGiftCardResponseData {
    #[serde(rename = "referenceNo", skip_serializing_if = "Option::is_none")]
    pub reference_no: Option<String>,
    #[serde(rename = "identityNo", skip_serializing_if = "Option::is_none")]
    pub identity_no: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
}

impl RedeemABinanceGiftCardResponseData {
    #[must_use]
    pub fn new() -> RedeemABinanceGiftCardResponseData {
        RedeemABinanceGiftCardResponseData {
            reference_no: None,
            identity_no: None,
            token: None,
            amount: None,
        }
    }
}
