/*
 * Binance Rebate REST API
 *
 * OpenAPI Specification for the Binance Rebate REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::rebate::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSpotRebateHistoryRecordsResponseDataDataInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i64>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
}

impl GetSpotRebateHistoryRecordsResponseDataDataInner {
    #[must_use]
    pub fn new() -> GetSpotRebateHistoryRecordsResponseDataDataInner {
        GetSpotRebateHistoryRecordsResponseDataDataInner {
            asset: None,
            r#type: None,
            amount: None,
            update_time: None,
        }
    }
}
