/*
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::simple_earn::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLockedPersonalLeftQuotaResponse {
    #[serde(rename = "leftPersonalQuota", skip_serializing_if = "Option::is_none")]
    pub left_personal_quota: Option<String>,
}

impl GetLockedPersonalLeftQuotaResponse {
    #[must_use]
    pub fn new() -> GetLockedPersonalLeftQuotaResponse {
        GetLockedPersonalLeftQuotaResponse {
            left_personal_quota: None,
        }
    }
}
