/*
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::simple_earn::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFlexibleSubscriptionRecordResponseRowsInner {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "purchaseId", skip_serializing_if = "Option::is_none")]
    pub purchase_id: Option<i64>,
    #[serde(rename = "productId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "sourceAccount", skip_serializing_if = "Option::is_none")]
    pub source_account: Option<String>,
    #[serde(rename = "amtFromSpot", skip_serializing_if = "Option::is_none")]
    pub amt_from_spot: Option<String>,
    #[serde(rename = "amtFromFunding", skip_serializing_if = "Option::is_none")]
    pub amt_from_funding: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl GetFlexibleSubscriptionRecordResponseRowsInner {
    #[must_use]
    pub fn new() -> GetFlexibleSubscriptionRecordResponseRowsInner {
        GetFlexibleSubscriptionRecordResponseRowsInner {
            amount: None,
            asset: None,
            time: None,
            purchase_id: None,
            product_id: None,
            r#type: None,
            source_account: None,
            amt_from_spot: None,
            amt_from_funding: None,
            status: None,
        }
    }
}
