/*
 * Binance Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::margin_trading::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrossMarginCollateralRatioResponseInnerCollateralsInner {
    #[serde(rename = "minUsdValue", skip_serializing_if = "Option::is_none")]
    pub min_usd_value: Option<String>,
    #[serde(rename = "maxUsdValue", skip_serializing_if = "Option::is_none")]
    pub max_usd_value: Option<String>,
    #[serde(rename = "discountRate", skip_serializing_if = "Option::is_none")]
    pub discount_rate: Option<String>,
}

impl CrossMarginCollateralRatioResponseInnerCollateralsInner {
    #[must_use]
    pub fn new() -> CrossMarginCollateralRatioResponseInnerCollateralsInner {
        CrossMarginCollateralRatioResponseInnerCollateralsInner {
            min_usd_value: None,
            max_usd_value: None,
            discount_rate: None,
        }
    }
}
